// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


function drawEndGame() {
  return /* () */0;
}

function loop(game, _) {
  var match = game[/* status */0];
  switch (match) {
    case 0 : 
    case 1 : 
    case 2 : 
        return /* () */0;
    
  }
}

window.onload = (function () {
    var gameOver = ( document.getElementById("game-over") );
    var executeLoop = function () {
      return loop(/* record */[
                  /* status : Stopped */0,
                  /* score */0
                ], gameOver);
    };
    setInterval(executeLoop, 16);
    return /* () */0;
  });

exports.drawEndGame = drawEndGame;
exports.loop        = loop;
/*  Not a pure module */
